name: food_sub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.1
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  cached_network_image: ^3.3.0
  jwt_decoder: ^2.0.1
  lottie: ^2.6.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  flutter_masked_text2: ^0.9.1
  firebase_app_check: ^0.2.1+13
  geolocator: ^9.0.2
  geocoding: ^2.0.2
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/